### ISSUE TITLE
Client freezes in Title Override Mode

### ISSUE THREAD

**Issue by KevinBlue28** [cy33hc/switch-ftp-client#2]
Is it normal for FTP Client to freeze when using Title Override?

**Comment by cy33hc** [comment]
@KevinBlue28 It shouldn't. What firmware are you on? I haven't checked compatibility since 14.0

**Comment by KevinBlue28** [comment]
Sorry I'm late, I need to fix up my GitHub notifications but I'm on version 16.1.0.

**Comment by KevinBlue28** [comment]
Never mind, I'll just close this issue because the problem I had was human error, my impatience. Thank you for developing this program.
